### ISSUE TITLE
test/T02.function.hpp

### ISSUE THREAD

**Issue by andriish** [RosettaCommons/binder#127]
Hi @lyskov ,

The test test/T02.function.hpp  dies include references to std::string, but does not include the <string> header. 

Hopefully the inclusion of <string> will eliminate the difference between binders generated on different platforms.

Best regards,

Andrii

**Comment by lyskov** [comment]
Hm... Binder is always generate `#include <string>` because it is needed for module-binding function. Please see: https://github.com/RosettaCommons/binder/blob/master/test/T02.function.ref#L18 and https://github.com/RosettaCommons/binder/blob/master/test/T02.function.ref#L27 . 

> Hopefully the inclusion of will eliminate the difference between binders generated on different platforms.

-- could you please elaborate on this? Missing header should be leading compilation error, which i assume was not the case?

**Comment by andriish** [comment]
Hi @lyskov ,

No, that was not the case. My assumption was that the binders are different because of different tree of includes in different stl implementations. In this case it would be better to have all needed includes in the hpp file explicitly. It looks there are cases like that, but not this one.  The problem here was actually #129 .

Best regards,
Andrii

**Comment by andriish** [comment]
>EDIT: Or do you mean that this test failed to compiled on some platforms?

Binder produced different codes on different platforms.

**Comment by lyskov** [comment]
Let me clarify: i do agree that `string` header should be added to this file. But i am not sure how this could help with tests instability: Binder results should not be dependent on include order.
