### ISSUE TITLE
test cases outdated

### ISSUE THREAD

**Issue by ThFe** [RosettaCommons/binder#153]
Hi @lyskov,
first of all: thanks a lot for this tool!

I just realised that many of the test case references seem to be out of date.
CTest does not report any discrepancies, but only because `--always-success` is being passed to `diffbinder`.  
This flag has been introduced in 902f6e7bec36ac4a5bae810d150c470626ea4b5e.
I think the flag needs to be removed and test cases updated. Do you agree?

P.S.: For most of the test cases, the differences can be resolved easily by removing some semi-colons - they are related to #152.
For some other test cases, however, like T42, the changes are more extensive.

**Comment by andriish** [comment]
Hi @ThFe ,

Updating the reference results is a good idea, as for me. But unfortunately the produced bindings are slightly different for different llvm versions, so the flag will be needed at least for some of them.
Of course one could redefine the compatibility range of the llvm versions, but I don't know which version of llvm is used by @lyskov now.

Best regards,

Andrii

**Comment by lyskov** [comment]
Thank you @ThFe , - glad you like it!

As @andriish pointed out the test output is different for different platform so we have to disable comparison steps for most of them. Our reference platform is CentOS-7 with default Clang install.

@andriish related, could you please remind me: we do have CentOS-7 tests now run without `--always-success` right? Or did we have to disable it? Thanks,

**Comment by andriish** [comment]
Hi @ThFe , @lyskov ,

The reference files came from @lyskov , from LLVM-6@CentOS7 installation. And for that configuration, there was no need for that flag. However, as far as I understand that LLVM-6@CentOS7 was compiled from sources. Means it was not possible to reproduce that configuration it in a fast CI -> github CI runs only on Fedora and MacOS, platforms where one can easily get  binary LLVM packages within minutes.

Now, back to the differences. Because the produced bindings depend not only on the LLVM version, but also on the used standard headers, the `--always-success`  was required in CI even for versions of LLVM which were close to LLVM-6.

Best regards,

Andrii

P.S. Actually, if the standard version of LLVM for Rosetta now LLVM7@CentOS7, one could easily add CentOS7 to CI and there should be no need for the flag at least for one CI config.

**Comment by ThFe** [comment]
Hi @andriish, @lyskov,

thanks a lot! I see the problem.
Having a reference platform (maybe also via a docker file?) on which the tests can be run successfully (i.e., without `--always-success`) would help a lot.

[The reason I asked this is related to an issue I faced with forward declared inner classes. I wanted to try to resolve it, but without breaking any functionality]

Best regards,
Thomas

**Comment by andriish** [comment]
Hi @ThFe ,

>Having a reference platform
@lyskov has a reference platform -- CentOS7. But according to my understanding for that reference platform @lyskov builds binder as a part of LLVM. So the "docker file" for the reference platform would be just "FROM centos:7" and then one has to start the build process according to https://cppbinder.readthedocs.io/en/latest/install.html .  Of course the compilation will take some CPU hours and the results (i.e. binder + libraries ) will be large, but for a large codebase like Rosetta it is not important at all.  For sure the process is not very convenient for smaller projects and I was patient enough to do that from scratch only twice or so, but well, that makes sense for the authors of OSS to write codes that solve their tasks best.

>I wanted to try to resolve it, but without breaking any functionality
OK. I see. Is there a LLVM version that works? If so, some small differences between the bindings generated with different LLVM versions e.g. in CI can be useful here. LLVM has only 6-8 months between the releases and binder uses only a fraction of LLVM functionality, so it is not too hard to spot the difference in the LLVM code between working and non-working versions.  Also, some differences are created just because of reordering of #include statements in the standard headers and can be safely ignored.


Best regards,

Andrii

**Comment by ThFe** [comment]
Hi @andriish,

thanks for your reply. I was almost expecting that binder is built as a part of LLVM in the reference system (I have read the docs, of course). You are certainly right - for smaller projects, this would be too much.

Regarding the forward declared inner class issue: I do not know whether there is an LLVM version that works (it does not for v11).
I´ll create a separate issue for that one.

Best regards,
Thomas

**Comment by andriish** [comment]
Hi @ThFe ,

With #154 the differences for T17 and T42 are observed for all versions of LLVM@Fedora (4.0-12).

For LLVM12 (Fedora34) there is a difference in T40
`class std::vector<int, class std::allocator<int> >` vs `class std::vector<int> `

Best regards,

Andrii

**Comment by ThFe** [comment]
Hi @andriish,
thanks a lot! Just as an info: with your changes, I do see differences for the same test cases (T17 and T42) on my sys (llvm11 on archlinux).
(For T17, it is just two more `#include <T17.anonymous.hpp>`.)
Best regards,
Thomas
