### ISSUE TITLE
Adding code in output main file

### ISSUE THREAD

**Issue by RedSkotina** [RosettaCommons/binder#17]
How i can add code (initialize global static variable of my lib) in output file?

**Comment by lyskov** [comment]
If you talking about adding arbitrary chunk of code that you want to execute before/after the import section then there is no such functionality at the moment. However, if all you want is to make sure your global variable is initialized properly then i think there is a better way to approach this: i would recommend to consider replacing global static data with global static functions and initialize your variable on-demand. Please see https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use-members for example and explanation why this is a good practice.

Also, please note that if you working on Windows platform then using this approach is really the only way to reliably achieve static initialization because DLL's does not automatically init c-runtime across DLL boundaries.

**Comment by RedSkotina** [comment]
Yes im talk about chunk of code.  Thanks for answer
