### ISSUE TITLE
Turn off exporting operator and program structure with multiple modules

### ISSUE THREAD

**Issue by trelau** [RosettaCommons/binder#21]
**Part 1:**
In the very simple test cases I've put together I see that Binder by default exports the assignment operator for a simple Rectangle class. I don't explicitly define it in C++ (maybe I should), but I can't compile the bindings with it in there and they seem to work ok when I comment it out. Is this bad practice from my end? Or should there be a way to tell Binder not to generate bindings for operators?

**Part 2:**
Eventually I'd like to tackle wrapping a large C++ project that will be made up of multiple interconnected modules. So in Python it will be something like:

from root-module.mod1 import Class1, ...
from root-module.mod2 import Class2, ...
from root-module.mod3 import Class3, ...

It looks like this can be accomplished using pybind11:module::import() before you declare a new module. Is there native functionality for this in Binder? It seems every dependency gets put in the source file.

Thanks,
Trevor

**Update:**
As a semi-automated first attempt at this, maybe there can be an option that binder will **only** generate bindings for items defined in all_includes.h (it won't go recursing into those headers and write bindings). And then in the config file you could have a +import modname flag that would insert the pybind11::module::import(modname)?

**Comment by lyskov** [comment]
Re part1: roots for this behavior is in C++ design, by default C++ compiler will automatically generate some of the member function including copy constructor and assignment operators (see more here https://stackoverflow.com/questions/4943958/conditions-for-automatic-generation-of-default-copy-move-ctor-and-copy-move-assi). So Binder just bind everything that is available. 

I see a few ways you can approach this:
1. You can explicitly delete assignment operator in your class (see http://en.cppreference.com/w/cpp/language/copy_assignment) or
2. You can use Binder config directive `-function operator=...` to disable bindings generation for this particular operator. (see http://cppbinder.readthedocs.io/en/latest/config.html#config-file-options)

I think [1] is best approach here but [2] will also work.

**Comment by lyskov** [comment]
Re part2: This should be possible. However i would recommend to consider alternative approaches to tackle this problem because of the following issues: when planning to split your bindings into multiple modules this will work well only if you have a clear hierarchy between each module and when no cross-reference is present. This might be the appropriate design when each module represent separate C++ library with clear dependency hierarchy.

However if code for each module is part of the same library/project then splitting code into such modules will be problematic due to cross-dependency. So instead it is better to have everything in one module and allow Binder to automatically manage import orders and sub-modules organization.

Now, about sub-modules: Binder will automatically place bindings for functions/classes/enums into appropriate submodules according to C++ namespaces they was define in. So for example if you have class `A` in C++ namespace `aaaa` then Binder will place it into `<root-module>.aaaa.A` so in Python you can just do `from <root-module>.aaaa import A`. This process is of course recursive so can have as many sub-modules as you need. So in practice if your C++ code organized reasonable well then you do not need to worry about sub-modules - Binder will do them for you automatically.

Let me know if you need more info on this,

**Comment by trelau** [comment]
@lyskov thank your for the info. I ended up on option two of part 1 last night but I'll revisit. 

For submodules, cross dependency is an issue, but my library doesn't have any namespaces. I have a script that generated the master list of include files, maybe as a hack I can put them in namespaces based on desired module name in that file?

**Comment by lyskov** [comment]
So... does your modules have cross references? If yes then i would argue that they really not separate modules and instead part of single module. Also please note that if you have such cross references then importing them in Python will be problematic since Python do not have forward declarations. So over all i would recommend to reconsider and examine design when everything goes into one module.

I guess automatically putting your includes in separate namespaces is an option too but please note that if your header files include each other then doing such namespace-workaround automatically will be problematic...

**Comment by lyskov** [comment]
Is this a public project? Can i look at the code? Maybe there is a simpler approach...

**Comment by trelau** [comment]
Thank you @lyskov for all the help. I tested the namespace in all_headers.h idea and it "worked" as far as putting things into modules, but you have find/replace all the namespaces in the sources since they don't exist before you compile. At the end of the day I think I'm unnecessarily making it harder than it needs to be in an attempt to organize the project. Just a single module is fine. Thanks for all your help. I'll go ahead and close the issue.

**Comment by lyskov** [comment]
Great, glad it helped!
