### ISSUE TITLE
Support for operator>> and operator<<

### ISSUE THREAD

**Issue by v-yatsenko** [RosettaCommons/binder#49]
https://github.com/RosettaCommons/binder/blob/0333a4db6aa16888b1afdcb58bf613d531b9b2cd/source/function.cpp#L42
Are there any reasons why operators like '>>', '<<' are not included in this list?
Pybind11 may deal with these.

**Comment by lyskov** [comment]
This is mostly due to historical reason: initially bindings to `ostream` and `istream` was not supported. It was also not clear how exactly map this into Python, but i guess we could try maping them to Python `__rlshift__` and `__rrshift__`. I can re-visit this if there is a demand for this so please let me know.

**Comment by v-yatsenko** [comment]
I have added shifting operators to list of supported in function.cpp:cpp_python_operator_map
So it may be used like this with object of type for which corresponding overloading is present:
o << 'something'
But can't mimic C++ like this:
o << 'string' << Number << Else

**Comment by ashhasthantra** [comment]
Is there any reason why operator < and > are not included in the cpp_python_operator_map? My C++ code base using < and >operators overloading. Having them included in the list would be helpful.

**Comment by lyskov** [comment]
@v-yatsenko how exactly was operators `<<` and `>>` implemented in C++? If they was implemented as `free` operators instead of member-operator-of-a-class then that would be a reason. For technical reason we currently can not bind such operators.

@ashhasthantra this just was not implement yet so i added it to my list. If you need to add support for this somewhat soon then PR adding this support will be welcome.
