### ISSUE TITLE
file_name_prefix_for_binder could not determent file name

### ISSUE THREAD

**Issue by Martinii89** [RosettaCommons/binder#77]
I'm getting a lot of these when running binder. 

> B{name=ObjectWrapper, path=
>  → 
> Warning: file_name_prefix_for_binder could not determent file name for decl: ObjectWrapper, result is too short!
> 

What is the requirement for the binder to deduce the correct filename? There's a bunch of files where it gets placed in unknown. Also a lot of classes are bunched together in the same file. Where the file will have the name of one of the classes. Is this intended behavior? 

[MyProject.zip](https://github.com/RosettaCommons/binder/files/3463734/MyProject.zip)

**Comment by lyskov** [comment]
@Martinii89 This is just a warning (so you can ignore it). And yes, this is intended behavior. In order for Binder to infer correct name of the include files such files need to be included with angel bracket instead of quotes. So for example:

1. `#include <my_file>` will work as intended and Binder will place generated code for objects from this file into file named ~ `my_file.XXX.cpp`.

2. `#include "my_file"` will produce the warning above and code will be placed into file with unknown prefix.

Hope this helps,

**Comment by lyskov** [comment]
Also, if your project uses namespace's then Binder will used object namespace path as dir path when generating source files.

**Comment by Martinii89** [comment]
In the input file to binder all my includes are done with angle brackets. Does the whole codebase need to use angle brackets for it not to be placed in unknown?

**Comment by lyskov** [comment]
Yes, in order for this to work angle brackets need to be used _in the library_ itself (in fact you can use quote-include in file that you feed to Binder - that one does not matter)
