### ISSUE TITLE
Include path

### ISSUE THREAD

**Issue by lczech** [RosettaCommons/binder#8]
The documentation should mention that the include path `bind -- -Ipath` needs to be absolute (at least on Ubuntu) to work.

**Comment by lyskov** [comment]
@lczech i just double checked on this and this is certainly not correct. In fact we do have code (last time ran just a few hours ago) that uses this directive and supply relative path (relative to current working directory). In fact all these options (`-I<path>` and `-isystem <path>`) is implemented on LLVM/Clang level so they function exactly like they do in Clang invocation. I guess double check your scripts?

**Comment by lczech** [comment]
Okay, thanks. I checked my scripts, and realized that i used `-I~/path/to/my/lib`. So the `~` as shorthand for my home directory does not work. Relative paths with `..` do work indeed. Sorry for the confusion.

**Comment by roccomoretti** [comment]
That's a standard shell foible, rather than being anything binder specific. The tilde (`~`) as a shortcut to your home directory is interpreted by the shell, rather than by any program. That is, Bash (or other shell) substitutes the proper value before the program even starts running. Where the shell does this substitution is rather specific, though. If the `~` is embedded in an argument, it's not expanded. So `~/path/to/my/lib` gets expanded properly, but `-I~/path/to/my/lib` does not. 

One thing that might work (I haven't tested this, though) is to use `-I ~/path/to/my/lib` instead of `-I~/path/to/my/lib` - that is, put a space between the `I` and the `~`. This way the shell will be able to properly expand the tilde before binder starts running.

**Comment by lczech** [comment]
Thanks, I know, bash (and probably no shell) substitutes `~` within arguments, for good reasons. In my script, it was basically just copy-paste error due to laziness, and then I prematurely opened this issue without double checking... Sorry again!
