### ISSUE TITLE
Making Binder aware of Eigen

### ISSUE THREAD

**Issue by cuihantao** [RosettaCommons/binder#85]
Hi there,

First of all, thanks for putting together this great tool, Binder. After a quick configuration, I was able to generate the binding code that would take days to write by hand. 

## Problem 
One issue I have with the generated code is the awareness of Eigen. Pybind11 has supported Eigen pretty well for the daily work (See https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html). 

Binder doesn't seem to recognize Eigen (or its namespace). If forced to do `-namespace Eigen`, it will omit all functions that has an Eigen argument. Otherwise, it will place Eigen files under `unknown` and produce a ton of warning, which looks like

```
Warning: file_name_prefix_for_binder could not determent file name for decl: Eigen::internal::Packet2cf, result is too short!
```
The compilation fails afterward.

## Reproduce
The attached is a minimum version of code using Eigen in a struct, modified from the `test_struct` example. A CMake build script is utilized. Note that the code will automatically clone Eigen into the folder root directory. You will also need to change a few hard-coded binder paths at the beginning of the script.

Kindly let me know if there's any workaround as well.

## Attachment
[binder.zip](https://github.com/RosettaCommons/binder/files/3751933/binder.zip)

**Comment by lyskov** [comment]
@cuihantao the warning above is just that - a warning, it should be ignored. It is emitted only to indicated that some of the type/functions could not be traced to it .hpp files. This usually happens when C++ uses relative includes like `#include "aa.hh"`. In such cases Binder can not determent location of include files and so compilation will fail (this limitation is documented here: https://cppbinder.readthedocs.io/en/latest/basics.html). You can workaround this issue by using `+include` directive in Binder config and force inclusion of some of Eigen headers.

re awareness of Eigen: - not sure what exactly do you mean by this but in general no special handling of third-party C++ libs should be needed: Binder will treat any library calls the same as any other C++ call. If you want to bind Eigen types in Python then you need to add `+namespace Eigen` directives into Binder config. This will trigger bindings generation for all functions/types in Eigen namespace.

**Comment by cuihantao** [comment]
Thanks for the reply. I guess I will try to include all the header files from Eigen. I will post an update once done.

**Comment by shiveshkhaitan** [comment]
@cuihantao were you able to figure out how to use Eigen with binder? I am facing exactly the same issue that you have mentioned.

**Comment by cuihantao** [comment]
> @cuihantao were you able to figure out how to use Eigen with binder? I am facing exactly the same issue that you have mentioned.

I was moved to another project and have not made any progress on this.

**Comment by shiveshkhaitan** [comment]
@cuihantao Thank you for letting me know

**Comment by shiveshkhaitan** [comment]
Found a workaround for now. Commenting out all the binder generated code containing `unknown` and not building the `unknown` files works.

**Comment by cuihantao** [comment]
> Found a workaround for now. Commenting out all the binder generated code containing `unknown` and not building the `unknown` files works.

I tried this workaround before. It turns out all C++ functions who returns an Eigen type are omitted from binding. 

Let me know what you discovered.

**Comment by shiveshkhaitan** [comment]
> I tried this workaround before. It turns out all C++ functions who returns an Eigen type are omitted from binding.

Not sure why that happened for you. The workaround works for me. You can find my changes in binder here https://github.com/shiveshkhaitan/binder

**Comment by cuihantao** [comment]
> > I tried this workaround before. It turns out all C++ functions who returns an Eigen type are omitted from binding.
> 
> Not sure why that happened for you. The workaround works for me. You can find my changes in binder here https://github.com/shiveshkhaitan/binder

Got it. Thanks.
